"use client";

import {
  Activity, AlertTriangle, ArrowRight, BarChart3, BellRing, CalendarDays, Check,
  CheckCircle2, ChevronDown, ChevronRight, CircleHelp, CloudCog, Download, Eye,
  FileDown, Filter, MapPin, PackageSearch, Plus, Radar, RefreshCw, Search,
  Settings2, SlidersHorizontal, Upload, X,
} from "lucide-react";
import { useMemo, useState } from "react";

type MainStatus = "NotFound" | "InfoReceived" | "InTransit" | "Expired" | "AvailableForPickup" | "OutForDelivery" | "DeliveryFailure" | "Delivered" | "Exception";
type AlertType = "超时未上网" | "轨迹停滞3天" | "7天未妥投" | "10天未妥投" | "海关停留超时" | "派送失败";
type Phase = "erp" | "info" | "pickup" | "export" | "customs" | "transit" | "arrival" | "delivery" | "delivered" | "pickup_point";

type TrackEvent = { time:string; phase:Phase; subStatus:string; description:string; location:string; source:"ERP"|"17TRACK"; abnormal?:boolean };
type Order = {
  id:string; orderNo:string; trackingNo:string; carrier:string; carrierCode:string; provider:string;
  channel:string; country:string; warehouse:string; platform:string; status:MainStatus; subStatus:string;
  shippedAt:string; pickupAt:string; deliveredAt:string; actualDays:string; slaDays:number; lastSync:string;
  latestEvent:string; latestAt:string; alert?:AlertType; alertAge?:string; severity?:"紧急"|"高"|"中"; events:TrackEvent[];
};

const STATUS = [
  ["NotFound","查询不到",7,"gray"],["InfoReceived","收到信息",18,"cyan"],["InTransit","运输途中",10,"blue"],
  ["Expired","运输过久",0,"orange"],["AvailableForPickup","到达待取",0,"purple"],["OutForDelivery","派送途中",2,"green"],
  ["DeliveryFailure","投递失败",4,"red"],["Delivered","已签收",2480,"emerald"],["Exception","可能异常",3,"rose"],
] as const;

const statusMeta = (key:MainStatus) => STATUS.find(s=>s[0]===key)!;

const EVENTS:TrackEvent[] = [
  {time:"2026-05-09 09:26",phase:"erp",subStatus:"ERP_Created",description:"履约单已创建",location:"OMS",source:"ERP"},
  {time:"2026-05-12 11:52",phase:"erp",subStatus:"ERP_Checkout",description:"仓库签出，完成物流交接",location:"USKY3-WINIT",source:"ERP"},
  {time:"2026-05-12 12:08",phase:"pickup",subStatus:"InTransit_PickedUp",description:"Shipment picked up",location:"Springfield Gardens, NY",source:"17TRACK"},
  {time:"2026-05-13 14:11",phase:"transit",subStatus:"InTransit_Other",description:"Processing at Designated Facility",location:"Linden, NJ",source:"17TRACK"},
  {time:"2026-05-14 19:33",phase:"delivery",subStatus:"OutForDelivery_Other",description:"Out for Delivery",location:"Newark, NJ",source:"17TRACK"},
  {time:"2026-05-15 01:49",phase:"delivery",subStatus:"DeliveryFailure_InvalidAddress",description:"Attempted Delivery: Invalid Address",location:"Newark, NJ",source:"17TRACK",abnormal:true},
];

const ORDERS:Order[] = [
  {id:"TN-SPXEWR079601274715",orderNo:"P260509004405",trackingNo:"SPXEWR079601274715",carrier:"SpeedX",carrierCode:"190844",provider:"SpeedX",channel:"WYT-WF5日达_Zonal",country:"US",warehouse:"USKY3-WINIT",platform:"PC1",status:"DeliveryFailure",subStatus:"DeliveryFailure_InvalidAddress",shippedAt:"2026-05-12 11:52",pickupAt:"2026-05-12 12:08",deliveredAt:"—",actualDays:"3.6天",slaDays:15,lastSync:"2026-05-23 17:47",latestEvent:"Attempted Delivery: Invalid Address",latestAt:"05-15 01:49",alert:"派送失败",alertAge:"持续 8天",severity:"高",events:EVENTS},
  {id:"TN-GFUS01050155127361",orderNo:"P260509004954",trackingNo:"GFUS01050155127361",carrier:"GOFO",carrierCode:"100996",provider:"GOFO",channel:"WYT-WF7日达_Zonal",country:"US",warehouse:"USKY3-WINIT",platform:"PC16",status:"Exception",subStatus:"Exception_Returning",shippedAt:"2026-05-11 09:44",pickupAt:"2026-05-11 09:56",deliveredAt:"—",actualDays:"10.6天",slaDays:15,lastSync:"2026-05-23 17:47",latestEvent:"Return Initiated",latestAt:"05-21 23:38",alert:"10天未妥投",alertAge:"10天 14小时",severity:"紧急",events:[...EVENTS.slice(0,4),{time:"2026-05-21 23:38",phase:"transit",subStatus:"Exception_Returning",description:"Return Initiated",location:"Melrose Park, IL",source:"17TRACK",abnormal:true}]},
  {id:"TN-9334920845500000037882",orderNo:"P260509004803",trackingNo:"9334920845500000037882",carrier:"万邑通",carrierCode:"190284",provider:"USPS",channel:"WYT-USPS GA签名服务",country:"US",warehouse:"USKY3-WINIT",platform:"PC1",status:"InTransit",subStatus:"InTransit_Other",shippedAt:"2026-05-11 23:30",pickupAt:"2026-05-11 21:12",deliveredAt:"—",actualDays:"—",slaDays:15,lastSync:"2026-05-23 17:47",latestEvent:"AVAILABLE FOR PICKUP",latestAt:"05-20 16:13",alert:"轨迹停滞3天",alertAge:"停滞 3天 1小时",severity:"高",events:[...EVENTS.slice(0,4),{time:"2026-05-20 16:13",phase:"pickup_point",subStatus:"AvailableForPickup_Other",description:"AVAILABLE FOR PICKUP",location:"San Leandro, CA",source:"17TRACK",abnormal:true}]},
  {id:"TN-YT260803881729",orderNo:"P26080300176",trackingNo:"YT260803881729",carrier:"云途物流",carrierCode:"190094",provider:"YunExpress",channel:"云途英国专线-无签",country:"GB",warehouse:"JY01",platform:"PC8",status:"InTransit",subStatus:"InTransit_CustomsProcessing",shippedAt:"2026-08-03 15:42",pickupAt:"2026-08-03 18:16",deliveredAt:"—",actualDays:"—",slaDays:15,lastSync:"2026-08-12 11:45",latestEvent:"Customs clearance processing",latestAt:"08-09 23:11",alert:"海关停留超时",alertAge:"停留 2天 9小时",severity:"中",events:[...EVENTS.slice(0,3),{time:"2026-08-07 03:40",phase:"export",subStatus:"InTransit_Departure",description:"Departed from origin airport",location:"Shenzhen, CN",source:"17TRACK"},{time:"2026-08-09 23:11",phase:"customs",subStatus:"InTransit_CustomsProcessing",description:"Customs clearance processing",location:"Heathrow, GB",source:"17TRACK",abnormal:true}]},
  {id:"TN-3PE260809412095",orderNo:"P26080900311",trackingNo:"3PE260809412095",carrier:"3PE EXPRESS",carrierCode:"191376",provider:"3pe",channel:"Luvme Express_XC01",country:"US",warehouse:"XC01",platform:"PC1",status:"InfoReceived",subStatus:"InfoReceived",shippedAt:"2026-08-09 08:30",pickupAt:"—",deliveredAt:"—",actualDays:"—",slaDays:15,lastSync:"2026-08-12 11:45",latestEvent:"Shipping Label Created",latestAt:"08-09 10:02",alert:"超时未上网",alertAge:"等待 3天 2小时",severity:"高",events:[{time:"2026-08-09 08:30",phase:"erp",subStatus:"ERP_Checkout",description:"仓库签出",location:"XC01",source:"ERP"},{time:"2026-08-09 10:02",phase:"info",subStatus:"InfoReceived",description:"Shipping Label Created",location:"",source:"17TRACK",abnormal:true}]},
  {id:"TN-3PE0163226352641",orderNo:"P260509004601",trackingNo:"3PE0163226352641",carrier:"3PE EXPRESS",carrierCode:"191376",provider:"3pe",channel:"Luvme Express_网红",country:"US",warehouse:"WH01",platform:"PC1",status:"Delivered",subStatus:"Delivered_Other",shippedAt:"2026-05-09 11:08",pickupAt:"2026-05-09 16:21",deliveredAt:"2026-05-15 08:42",actualDays:"5.9天",slaDays:15,lastSync:"2026-05-23 17:47",latestEvent:"Delivered, Front Door/Porch",latestAt:"05-15 08:42",events:[...EVENTS.slice(0,4),{time:"2026-05-15 08:42",phase:"delivered",subStatus:"Delivered_Other",description:"Delivered, Front Door/Porch",location:"New York, NY",source:"17TRACK"}]},
];

const ALERTS:[AlertType,number,string][] = [["超时未上网",18,"48h"],["轨迹停滞3天",31,"72h"],["7天未妥投",42,"7d"],["10天未妥投",12,"10d"],["海关停留超时",9,"48h"],["派送失败",23,"状态"]];
const NAV = [{id:"monitor",label:"监控中心",icon:BellRing,badge:112},{id:"tracking",label:"订单追踪",icon:PackageSearch},{id:"analytics",label:"履约分析",icon:BarChart3},{id:"rules",label:"规则配置",icon:CloudCog}];

function StatusBadge({status}:{status:MainStatus}) { const m=statusMeta(status); return <span className={`status status-${m[3]}`}><i/>{m[1]}</span> }
function Header({title,desc,actions}:{title:string;desc:string;actions?:React.ReactNode}) { return <div className="page-head"><div><h1>{title}</h1><p>{desc}</p></div><div className="actions">{actions}</div></div> }
function severity(s?:string){return s==="紧急"?"critical":s==="高"?"high":"medium"}

function StatusRail({onPick}:{onPick:(s:MainStatus)=>void}) { return <div className="status-rail">{STATUS.map(s=><button key={s[0]} onClick={()=>onPick(s[0])} className={`rail-${s[3]}`}><span>{s[1]}<i/></span><strong>{s[2].toLocaleString()}</strong><small>{s[0]}</small></button>)}</div> }

function AlertTable({orders,onOpen}:{orders:Order[];onOpen:(o:Order)=>void}) { return <div className="table-scroll"><table className="orders-table alert-orders"><thead><tr><th>预警</th><th>履约单 / 订单</th><th>17TRACK 状态</th><th>运单 / 渠道</th><th>最新轨迹</th><th>持续时间</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id} onClick={()=>onOpen(o)}><td><span className={`level ${severity(o.severity)}`}>{o.severity}</span><b>{o.alert}</b></td><td><strong>{o.id}</strong><small>{o.orderNo} · {o.platform}</small></td><td><StatusBadge status={o.status}/><code>{o.subStatus}</code></td><td><strong>{o.trackingNo}</strong><small>{o.carrier} · {o.channel}</small></td><td><strong className="ellipsis">{o.latestEvent}</strong><small>{o.latestAt}</small></td><td><strong>{o.alertAge}</strong></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div> }

function Monitor({toTracking,onOpen,notify}:{toTracking:(s?:MainStatus)=>void;onOpen:(o:Order)=>void;notify:(t:string)=>void}) {
  const [type,setType]=useState<string>("全部预警"); const [query,setQuery]=useState("");
  const rows=ORDERS.filter(o=>o.alert&&(type==="全部预警"||o.alert===type)&&(!query||[o.id,o.orderNo,o.trackingNo].join(" ").toLowerCase().includes(query.toLowerCase())));
  return <><Header title="监控中心" desc="今天只处理一件事：找出需要跟进的异常履约单。" actions={<><button className="btn"><CalendarDays size={15}/>近30天<ChevronDown size={13}/></button><button className="btn primary" onClick={()=>notify("已更新全部未妥投订单")}><RefreshCw size={15}/>更新轨迹</button></>}/>
    <div className="health"><div><i/><strong>监控正常</strong><span>ERP 与 17TRACK 最后同步 11:45 · 覆盖 2,506 单</span></div><div><span>活跃预警</span><strong>112</strong></div><div><span>今日新增</span><strong>26</strong></div><div><span>今日恢复</span><strong>21</strong></div><div><span>自动恢复率</span><strong>76.8%</strong></div></div>
    <StatusRail onPick={s=>toTracking(s)}/>
    <section className="panel monitor-panel"><div className="alert-filter">{ALERTS.map(a=><button key={a[0]} className={type===a[0]?"active":""} onClick={()=>setType(type===a[0]?"全部预警":a[0])}><span>{a[0]}</span><strong>{a[1]}</strong><small>{a[2]}</small></button>)}</div><div className="table-tools"><div><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索异常履约单、订单或运单"/></div><select><option>全部风险</option><option>紧急</option><option>高</option><option>中</option></select><select><option>全部物流商</option><option>SpeedX</option><option>GOFO</option></select><button><Filter size={14}/>筛选</button><span>{rows.length} 条示例 / 112 条</span></div><AlertTable orders={rows} onOpen={onOpen}/><div className="pager"><span>按风险等级与持续时间排序</span><button onClick={()=>toTracking()}>查看全部订单<ArrowRight size={13}/></button></div></section>
  </>;
}

function Tracking({initialStatus,onOpen,notify}:{initialStatus:string;onOpen:(o:Order)=>void;notify:(t:string)=>void}) {
  const [query,setQuery]=useState(""); const [status,setStatus]=useState(initialStatus||"全部状态");
  const filtered=ORDERS.filter(o=>(status==="全部状态"||o.status===status)&&(!query||[o.id,o.orderNo,o.trackingNo].join(" ").toLowerCase().includes(query.toLowerCase())));
  return <><Header title="订单追踪" desc="查订单、看当前状态与完整轨迹；异常判断仍回到监控中心。" actions={<><button className="btn" onClick={()=>notify("履约单导入已准备")}><Upload size={15}/>导入</button><button className="btn" onClick={()=>notify("已导出 CSV")}><FileDown size={15}/>导出</button><button className="btn primary" onClick={()=>notify("轨迹已更新")}><RefreshCw size={15}/>更新</button></>}/>
    <section className="panel tracking"><div className="track-search"><div><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索履约单号、ERP订单号或运单号"/></div><button className="btn"><Plus size={15}/>添加追踪</button></div><div className="filter-row"><select><option>全部承运商</option><option>SpeedX</option><option>GOFO</option><option>3PE EXPRESS</option></select><select><option>全部国家</option><option>US · 美国</option><option>GB · 英国</option></select><select><option>全部仓库</option><option>USKY3-WINIT</option><option>XC01</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option>全部状态</option>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]} · {s[0]}</option>)}</select><button><SlidersHorizontal size={14}/>更多筛选</button><span>共 2,506 单</span></div><div className="table-scroll"><table className="orders-table tracking-table"><thead><tr><th>履约单 / ERP订单</th><th>运单号</th><th>承运商</th><th>国家 / 仓库</th><th>17TRACK 状态</th><th>出库时间</th><th>渠道</th><th>实际 / SLA</th><th></th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} onClick={()=>onOpen(o)}><td><strong>{o.id}</strong><small>{o.orderNo} · {o.platform}</small></td><td><strong>{o.trackingNo}</strong><small>carrier code {o.carrierCode}</small></td><td><strong>{o.carrier}</strong><small>{o.provider}</small></td><td><strong>{o.country}</strong><small>{o.warehouse}</small></td><td><StatusBadge status={o.status}/><code>{o.subStatus}</code></td><td><strong>{o.shippedAt.split(" ")[0]}</strong><small>{o.shippedAt.split(" ")[1]}</small></td><td><strong>{o.channel}</strong></td><td><strong>{o.actualDays}</strong><small>SLA {o.slaDays}天</small></td><td><Eye size={16}/></td></tr>)}</tbody></table></div><div className="pager"><span>显示 1—{filtered.length} 条，共 2,506 条</span><div><button className="active">1</button><button>2</button><button>3</button><button>下一页</button></div></div></section>
  </>;
}

function Analytics(){ const [days,setDays]=useState(7); const rate=days<=3?"54.2%":days<=5?"81.7%":days<=7?"93.7%":"97.9%"; return <><Header title="履约分析" desc="只回答时效表现与问题集中在哪里。" actions={<button className="btn"><Download size={15}/>导出</button>}/><div className="analysis-filter"><select><option>按物流渠道</option><option>按团队</option><option>按仓库</option><option>按国家</option><option>按州</option><option>按邮编</option></select><select><option>全部仓库</option></select><select><option>全部国家</option></select><label><input type="number" value={days} onChange={e=>setDays(Number(e.target.value))}/><span>天达成率</span></label><button className="btn primary">应用</button></div><div className="analysis-kpi"><div><span>{days}天达成率</span><strong>{rate}</strong><small>环比 +1.8%</small></div><div><span>平均签出 → 签收</span><strong>4.6天</strong><small>较目标快 2.4天</small></div><div><span>P90履约时效</span><strong>6.8天</strong><small>样本 2,506 单</small></div><div><span>SLA超时</span><strong>1.04%</strong><small>26 单</small></div></div><div className="analysis-grid"><section className="panel"><div className="panel-title"><div><h2>{days}天达成率趋势</h2><p>最近12周 · 按签出日期</p></div><b>目标 ≥ 92%</b></div><div className="bars">{[84,88,87,90,91,89,93,94,92,95,94,96].map((v,i)=><div key={i}><i style={{height:`${(v-70)*4}px`}}/><strong>{v}%</strong><span>{i+1}周</span></div>)}</div></section><section className="panel"><div className="panel-title"><div><h2>渠道达成率</h2><p>订单量 ≥ 30</p></div></div>{[["WYT-WF5日达",96.2,1420],["Luvme Express",94.8,486],["SpeedX Zonal",93.4,352],["云途英国专线",89.6,148],["USPS GA签名",84.1,100]].map(x=><div className="rank" key={x[0]}><div><strong>{x[0]}</strong><span>{x[2]}单</span></div><i><b style={{width:`${Number(x[1])-20}%`}}/></i><strong className={Number(x[1])<90?"bad":""}>{x[1]}%</strong></div>)}</section></div></> }

function Rules({notify}:{notify:(t:string)=>void}){ const rules=[["超时未上网","erp_checkout_time","无 InTransit_PickedUp","48小时","高"],["轨迹停滞3天","最后有效轨迹","主状态 ≠ Delivered","72小时","高"],["7天未妥投","erp_checkout_time","主状态 ≠ Delivered","7天","中"],["10天未妥投","erp_checkout_time","主状态 ≠ Delivered","10天","紧急"],["海关停留超时","CustomsProcessing","无 CustomsReleased","48小时","中"],["派送失败","DeliveryFailure","读取 DeliveryFailure_*","即时","高"]]; return <><Header title="规则配置" desc="维护监控口径；状态字典不再单独占用一个模块。" actions={<button className="btn primary" onClick={()=>notify("规则已保存")}><Check size={15}/>保存</button>}/><div className="rules-layout"><section className="panel rules"><div className="rule-head"><span>启用</span><span>规则</span><span>时间起点</span><span>17TRACK条件</span><span>阈值</span><span>级别</span></div>{rules.map((r,i)=><div className="rule" key={r[0]}><button className="switch on"><i/></button><div><strong>{r[0]}</strong><small>R-0{i+1}</small></div><code>{r[1]}</code><code>{r[2]}</code><button className="threshold">{r[3]}</button><span className={`level ${severity(r[4])}`}>{r[4]}</span></div>)}</section><aside className="panel rule-help"><h2>关键口径</h2><div><b>真实上网</b><code>InTransit_PickedUp</code><span>Shipping Label Created 不算上网</span></div><div><b>海关放行</b><code>InTransit_CustomsReleased</code><span>出现后自动解除海关预警</span></div><div><b>妥投终态</b><code>Delivered</code><span>关闭未妥投类预警</span></div><p><Activity size={15}/>规则每15分钟扫描；未妥投订单每4小时刷新17TRACK。</p></aside></div></> }

function Drawer({order,onClose,notify}:{order:Order;onClose:()=>void;notify:(t:string)=>void}){ const [tab,setTab]=useState("轨迹"); return <div className="drawer-mask" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><header><div><span>履约单详情</span><h2>{order.id}</h2><p>{order.orderNo} · {order.trackingNo}</p></div><button onClick={onClose}><X size={18}/></button></header><div className="drawer-state"><StatusBadge status={order.status}/><code>{order.subStatus}</code>{order.alert&&<span className={`level ${severity(order.severity)}`}>{order.alert}</span>}<button onClick={()=>notify("已刷新该运单轨迹")}><RefreshCw size={14}/>刷新</button></div><div className="drawer-body"><div className="drawer-metrics"><div><span>实际时效</span><strong>{order.actualDays}</strong></div><div><span>SLA</span><strong>{order.slaDays}天</strong></div><div><span>上网时间</span><strong>{order.pickupAt}</strong></div><div><span>最后同步</span><strong>{order.lastSync}</strong></div></div>{order.alert&&<div className="why"><AlertTriangle size={18}/><div><strong>{order.alert} · {order.alertAge}</strong><p>{order.alert==="超时未上网"?"ERP已签出超过48小时，但轨迹仍为InfoReceived，未出现InTransit_PickedUp。":order.alert==="派送失败"?`17TRACK返回 ${order.subStatus}，等待重派、退回或签收。`:"当前轨迹节点或履约总时长已超过配置阈值。"}</p></div></div>}<div className="drawer-tabs">{["轨迹","ERP信息","监控判断"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{tab==="轨迹"&&<div className="timeline">{order.events.slice().reverse().map((e,i)=><article className={e.abnormal?"abnormal":""} key={e.time+i}><i className={`phase-${e.phase}`}/><time>{e.time}</time><div><span>{e.phase} · {e.source}</span><code>{e.subStatus}</code><strong>{e.description}</strong>{e.location&&<small><MapPin size={11}/>{e.location}</small>}</div></article>)}</div>}{tab==="ERP信息"&&<div className="info-grid">{[["ERP订单号",order.orderNo],["平台",order.platform],["发货仓",order.warehouse],["目的国家",order.country],["签出时间",order.shippedAt],["物流渠道",order.channel]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div>}{tab==="监控判断"&&<div className="diagnosis">{[[order.pickupAt!=="—","真实上网",order.pickupAt!=="—"?`已出现 InTransit_PickedUp · ${order.pickupAt}`:"尚未出现 InTransit_PickedUp"],[order.status==="Delivered","妥投状态",order.status==="Delivered"?"已妥投":"尚未出现 Delivered"],[true,"数据归属","ERP负责履约字段，17TRACK负责状态与轨迹"]].map(x=><div className={x[0]?"pass":"hit"} key={String(x[1])}>{x[0]?<CheckCircle2/>:<AlertTriangle/>}<section><strong>{x[1]}</strong><span>{x[2]}</span></section></div>)}</div>}</div></aside></div> }

export default function Home(){ const [active,setActive]=useState("monitor"); const [status,setStatus]=useState(""); const [open,setOpen]=useState<Order|null>(null); const [toast,setToast]=useState(""); const notify=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),2200)}; const toTracking=(s?:MainStatus)=>{setStatus(s||"");setActive("tracking")}; const page=useMemo(()=>active==="monitor"?<Monitor toTracking={toTracking} onOpen={setOpen} notify={notify}/>:active==="tracking"?<Tracking initialStatus={status} onOpen={setOpen} notify={notify}/>:active==="analytics"?<Analytics/>:<Rules notify={notify}/>,[active,status]); return <div className="app"><aside className="sidebar"><div className="brand"><div><Radar size={22}/></div><section><strong>履约雷达</strong><span>17TRACK CONTROL TOWER</span></section></div><nav>{NAV.map(({id,label,icon:Icon,badge})=><button className={active===id?"active":""} key={id} onClick={()=>{setActive(id);if(id!=="tracking")setStatus("")}}><Icon size={18}/><span>{label}</span>{badge&&<b>{badge}</b>}</button>)}</nav><div className="side-label">数据连接</div><div className="connection"><p><i/>ERP履约数据 <b>正常</b></p><p><i/>17TRACK API <b>正常</b></p><small>最后同步 11:45<br/>覆盖 2,506 单</small></div><div className="profile"><span>Z</span><div><strong>张敏</strong><small>履约运营经理</small></div><ChevronDown size={14}/></div></aside><main><header className="topbar"><div><span>履约监控</span><ChevronRight size={12}/><strong>{NAV.find(n=>n.id===active)?.label}</strong></div><section><button onClick={()=>toTracking()}><Search size={14}/>搜索订单</button><button aria-label="帮助"><CircleHelp size={17}/></button></section></header><div className="content">{page}</div></main>{open&&<Drawer order={open} onClose={()=>setOpen(null)} notify={notify}/>} {toast&&<div className="toast"><CheckCircle2 size={16}/>{toast}</div>}</div> }
